import numpy as np
d1=np.array([1,2,2,4,5,6])
d2=np.array([1,4,8,5,9])
print(np.mean(d1))
print(np.sum(d1))
print(np.sqrt(d1))
print(np.exp(d1))
arr1=np.eye(2,3)
print(arr1)
arr2=np.ones((2,3))
print(arr2)
arr3=np.zeros((3,4))
print(arr3)
arr4=np.arange(1,10,2)
print(arr4)
arr5=np.linspace(1,10,5)
print(arr5)
arr6=np.random.rand(2,4)
print(arr6)
print(np.min(d1))
print(np.max(d1))
print(np.sort(d1))
print(np.min(d2))
print(np.max(d2))
print(np.sort(d2))
print(np.sum(d2))
print(np.sqrt(d2))
print(np.exp(d2))


